import os
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from dotenv import load_dotenv
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
import pickle

load_dotenv()

# Gmail API scopes
SCOPES = ['https://www.googleapis.com/auth/gmail.send']

class EmailService:
    def __init__(self):
        self.credentials_file = os.getenv("GMAIL_CREDENTIALS_FILE", "credentials.json")
        self.token_file = os.getenv("GMAIL_TOKEN_FILE", "token.pickle")
        self.from_email = os.getenv("FROM_EMAIL")
        self.service = None
        self.enabled = False
        
        try:
            self.service = self._get_gmail_service()
            self.enabled = self.service is not None
            if self.enabled:
                print("[EMAIL SERVICE] ✅ Gmail API initialized successfully")
            else:
                print("[EMAIL SERVICE] ⚠️  Gmail API not configured - email sending disabled")
        except Exception as e:
            print(f"[EMAIL SERVICE] ⚠️  Failed to initialize Gmail API: {e}")
            print("[EMAIL SERVICE] Email sending will be disabled")
    
    def _get_gmail_service(self):
        """Get Gmail API service using OAuth 2.0"""
        creds = None
        
        # Check if we have a valid token file
        if os.path.exists(self.token_file):
            try:
                with open(self.token_file, 'rb') as token:
                    creds = pickle.load(token)
                    print("[EMAIL SERVICE] Loaded existing credentials from token.pickle")
            except Exception as e:
                print(f"[EMAIL SERVICE] ⚠️  Error loading token file: {e}")
        
        # If credentials are invalid or don't exist, get new ones
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                try:
                    print("[EMAIL SERVICE] Refreshing expired credentials...")
                    creds.refresh(Request())
                    print("[EMAIL SERVICE] ✅ Credentials refreshed")
                except Exception as e:
                    print(f"[EMAIL SERVICE] ⚠️  Error refreshing credentials: {e}")
                    creds = None
            
            if not creds:
                # Check if credentials file exists
                if not os.path.exists(self.credentials_file):
                    print(f"[EMAIL SERVICE] ⚠️  Credentials file not found: {self.credentials_file}")
                    print("[EMAIL SERVICE] Please download OAuth credentials from Google Cloud Console")
                    print("[EMAIL SERVICE] See documentation for setup instructions")
                    return None
                
                try:
                    print(f"[EMAIL SERVICE] Starting OAuth flow with {self.credentials_file}...")
                    flow = InstalledAppFlow.from_client_secrets_file(
                        self.credentials_file, SCOPES)
                    # Run local server for OAuth
                    creds = flow.run_local_server(port=0)
                    print("[EMAIL SERVICE] ✅ OAuth authorization completed")
                except Exception as e:
                    print(f"[EMAIL SERVICE] ⚠️  OAuth flow failed: {e}")
                    return None
            
            # Save credentials for future use
            try:
                with open(self.token_file, 'wb') as token:
                    pickle.dump(creds, token)
                    print(f"[EMAIL SERVICE] Credentials saved to {self.token_file}")
            except Exception as e:
                print(f"[EMAIL SERVICE] ⚠️  Error saving credentials: {e}")
        
        try:
            service = build('gmail', 'v1', credentials=creds)
            return service
        except Exception as e:
            print(f"[EMAIL SERVICE] ⚠️  Error building Gmail service: {e}")
            return None
    
    def send_summary_email(
        self, 
        to_email: str, 
        x_username: str, 
        summary: str, 
        tweets_count: int,
        topics: Optional[list] = None
    ) -> bool:
        """
        Send AI summary via email using Gmail API
        """
        # Create email body
        topics_text = f"\nTopics of interest: {', '.join(topics)}\n" if topics else ""
        
        text_content = f"""XTrack Summary Report

Account: @{x_username}
Tweets analyzed: {tweets_count}
{topics_text}
Summary:
{summary}

---
Generated by XTrack
"""
        
        html_content = f"""<html>
<head></head>
<body>
    <h2>XTrack Summary Report</h2>
    <p><strong>Account:</strong> @{x_username}</p>
    <p><strong>Tweets analyzed:</strong> {tweets_count}</p>
    {f'<p><strong>Topics of interest:</strong> {", ".join(topics)}</p>' if topics else ''}
    <hr>
    <h3>AI Summary</h3>
    <div style="white-space: pre-wrap; line-height: 1.6;">{summary}</div>
    <hr>
    <p style="color: #666; font-size: 0.9em;">Generated by XTrack</p>
</body>
</html>"""
        
        subject = f"XTrack Summary: @{x_username}"
        
        return self.send_email(to_email, subject, text_content, html_content)
    
    def send_email(self, recipient_email: str, subject: str, body_text: str, body_html: Optional[str] = None):
        """Send email using Gmail API"""
        if not self.enabled:
            print(f"[EMAIL SERVICE] ⚠️  Email service disabled. Would have sent to {recipient_email}")
            print(f"[EMAIL SERVICE] Subject: {subject}")
            return False
        
        if not recipient_email:
            print("[EMAIL SERVICE] ❌ No recipient email provided")
            return False
        
        try:
            print(f"[EMAIL SERVICE] Preparing email to {recipient_email}...")
            
            # Create message
            message = MIMEMultipart('alternative')
            message['To'] = recipient_email
            message['From'] = self.from_email or 'me'
            message['Subject'] = subject
            
            # Attach plain text
            part1 = MIMEText(body_text, 'plain')
            message.attach(part1)
            
            # Attach HTML if provided
            if body_html:
                part2 = MIMEText(body_html, 'html')
                message.attach(part2)
            
            # Encode message
            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
            
            print(f"[EMAIL SERVICE] Sending email via Gmail API...")
            # Send message
            send_message = self.service.users().messages().send(
                userId='me',
                body={'raw': raw_message}
            ).execute()
            
            print(f"[EMAIL SERVICE] ✅ Email sent successfully to {recipient_email}")
            print(f"[EMAIL SERVICE] Message ID: {send_message.get('id')}")
            return True
            
        except Exception as e:
            print(f"[EMAIL SERVICE] ❌ Failed to send email to {recipient_email}: {e}")
            import traceback
            print(f"[EMAIL SERVICE] Traceback: {traceback.format_exc()}")
            return False

