"""
SendGrid Email Service
Uses SendGrid API for reliable email delivery
"""
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content
from typing import Optional, List
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

class SendGridService:
    """SendGrid email service for sending notifications"""
    
    def __init__(self):
        self.api_key = os.getenv("SENDGRID_API_KEY")
        self.from_email = os.getenv("FROM_EMAIL", "kai@ai-productivity.tools")
        self.enabled = bool(self.api_key)
        
        if self.enabled:
            self.client = SendGridAPIClient(self.api_key)
            print(f"[SENDGRID] ✅ SendGrid initialized successfully (from: {self.from_email})")
        else:
            print("[SENDGRID] ⚠️  SendGrid not configured - email sending disabled")
            print("[SENDGRID] Please set SENDGRID_API_KEY environment variable")
    
    def send_email(self, to_email: str, subject: str, text_content: str, html_content: str) -> bool:
        """
        Send an email using SendGrid
        
        Args:
            to_email: Recipient email address
            subject: Email subject
            text_content: Plain text content
            html_content: HTML content
            
        Returns:
            bool: True if email sent successfully, False otherwise
        """
        if not self.enabled:
            print(f"[SENDGRID] ⚠️  Cannot send email - SendGrid not configured")
            return False
        
        if not to_email:
            print(f"[SENDGRID] ⚠️  Cannot send email - no recipient email provided")
            return False

        try:
            message = Mail(
                from_email=Email(self.from_email, 'XTrack'),
                to_emails=To(to_email),
                subject=subject,
                plain_text_content=Content("text/plain", text_content),
                html_content=Content("text/html", html_content)
            )
            
            print(f"[SENDGRID] Sending email to {to_email}...")
            print(f"[SENDGRID] Subject: {subject}")
            response = self.client.send(message)
            
            if response.status_code in [200, 201, 202]:
                print(f"[SENDGRID] ✅ Email sent successfully! Status: {response.status_code}")
                return True
            else:
                print(f"[SENDGRID] ⚠️  Unexpected status code: {response.status_code}")
                print(f"[SENDGRID] Response body: {response.body}")
                return False
                
        except Exception as e:
            print(f"[SENDGRID] ❌ Error sending email: {str(e)}")
            import traceback
            print(f"[SENDGRID] Traceback: {traceback.format_exc()}")
            return False

    def send_summary_email(
        self, 
        to_email: str, 
        x_username: str, 
        summary: str, 
        tweets_count: int,
        topics: Optional[List[str]] = None
    ) -> bool:
        """
        Send AI summary via email using SendGrid
        
        Args:
            to_email: Recipient email address
            x_username: X/Twitter username being monitored
            summary: AI-generated summary text
            tweets_count: Number of tweets analyzed
            topics: Optional list of topics of interest
            
        Returns:
            bool: True if email sent successfully, False otherwise
        """
        # Create email body
        topics_text = f"\nTopics of interest: {', '.join(topics)}\n" if topics else ""
        
        text_content = f"""XTrack Summary Report

Account: @{x_username}
Tweets analyzed: {tweets_count}
{topics_text}
Summary:
{summary}

---
Generated by XTrack
"""
        
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #1a1a1a; margin: 0; padding: 20px; background-color: #f5f5f5;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
        <!-- Header -->
        <div style="background-color: #1a1a1a; color: #ffffff; padding: 20px; text-align: center;">
            <h1 style="margin: 0; font-size: 24px; font-weight: 600;">XTrack Summary Report</h1>
        </div>
        
        <!-- Content -->
        <div style="padding: 30px;">
            <!-- Meta Information -->
            <div style="background-color: #f9f9f9; padding: 15px; margin-bottom: 20px; border-radius: 4px;">
                <p style="margin: 0 0 10px 0;"><strong>Account:</strong> @{x_username}</p>
                <p style="margin: 0 0 10px 0;"><strong>Tweets analyzed:</strong> {tweets_count}</p>
                {f'<p style="margin: 0;"><strong>Topics of interest:</strong> {", ".join(topics)}</p>' if topics else ''}
            </div>
            
            <!-- Summary Section -->
            <h2 style="color: #1a1a1a; font-size: 18px; margin: 0 0 15px 0; font-weight: 600;">AI Summary</h2>
            <div style="background-color: #f9f9f9; padding: 20px; border-radius: 4px; white-space: pre-wrap; line-height: 1.8; font-size: 14px;">
{summary}
            </div>
        </div>
        
        <!-- Footer -->
        <div style="background-color: #f5f5f5; padding: 20px; text-align: center; border-top: 1px solid #e5e5e5;">
            <p style="margin: 0; color: #666666; font-size: 13px;">Generated by <strong>XTrack</strong></p>
            <p style="margin: 10px 0 0 0; color: #999999; font-size: 12px;">
                Automated X/Twitter account monitoring and AI summarization
            </p>
        </div>
    </div>
</body>
</html>"""
        
        subject = f"XTrack Summary: @{x_username} ({generated_at})"
        if topics:
            subject += f" - {', '.join(topics[:2])}"  # Add first 2 topics to subject
        
        return self.send_email(to_email, subject, text_content, html_content)
