"""Add job_executions table and update summaries for playground support

Revision ID: dbfeb162846a
Revises: 
Create Date: 2025-12-29 22:20:16.619101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfeb162846a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create job_executions table
    op.create_table('job_executions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tweets_fetched', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_executions_created_at'), 'job_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_executions_job_id'), 'job_executions', ['job_id'], unique=False)
    
    # Update summaries table
    op.add_column('summaries', sa.Column('execution_id', sa.Integer(), nullable=True))
    op.add_column('summaries', sa.Column('is_playground', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('summaries', sa.Column('x_username', sa.String(length=255), nullable=True))
    op.add_column('summaries', sa.Column('topics', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('hours_back', sa.Integer(), nullable=True))
    op.alter_column('summaries', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_summaries_execution_id'), 'summaries', ['execution_id'], unique=False)
    op.create_index(op.f('ix_summaries_is_playground'), 'summaries', ['is_playground'], unique=False)
    op.create_foreign_key(None, 'summaries', 'job_executions', ['execution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert summaries table changes
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_index(op.f('ix_summaries_is_playground'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_execution_id'), table_name='summaries')
    op.alter_column('summaries', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('summaries', 'hours_back')
    op.drop_column('summaries', 'topics')
    op.drop_column('summaries', 'x_username')
    op.drop_column('summaries', 'is_playground')
    op.drop_column('summaries', 'execution_id')
    
    # Drop job_executions table
    op.drop_index(op.f('ix_job_executions_job_id'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_created_at'), table_name='job_executions')
    op.drop_table('job_executions')
    # ### end Alembic commands ###
